version: '3.8'

services:
  # Сервис для MySQL
  db:
    image: mysql:8.0
    container_name: mysql_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: myDB_kurs
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    volumes:
      - ./myDB_kurs.sql:/docker-entrypoint-initdb.d/init.sql  # Инициализация БД
      - db_data:/var/lib/mysql                                # Том для данных БД
    ports:
      - "3306:3306"
    networks:
        - webnet

  # Сервис для PHPMyAdmin
  phpmyadmin:
    image: phpmyadmin:latest
    container_name: phpmyadmin
    restart: always
    depends_on:
      - db
    environment:
      PMA_HOST: db
      PMA_PORT: 3306
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "8080:80"
    networks:
      - webnet

  # Сервис для веб-сервера (Apache + PHP)
  web:
    build: .  # Указывает на создание контейнера через Dockerfile
    container_name: web_server
    restart: always
    depends_on:
      - db
    volumes:
      - ./src:/var/www/html/ # пиппип
    ports:
      - "80:80"
    networks:
      - webnet

volumes:
  db_data:  # Том для хранения данных БД

networks:
  webnet:
    driver: bridge